### ISSUE TITLE
Proxy-Init doesn't work when logged into LhcbStarterKit

### ISSUE THREAD

**Issue by renqgl90** [lhcb/first-analysis-steps#105]
Log:
[rquaglia@~/StarterKit/Steps$|=>lhcb-proxy-init 
Generating proxy... 
Enter Certificate password:
Could not add VOMS extensions to the proxy
Failed adding VOMS attribute: Failed to set VOMS attributes. Command: voms-proxy-init -cert "/tmp/x509up_u69481" -key "/tmp/x509up_u69481" -out "/tmp/rquaglia/tmp9dHr7i" -voms "lhcb:/lhcb/Role=user" -valid "23:54" -vomses "/afs/cern.ch/lhcb/software/releases/DIRAC/DIRAC_v6r12p33/etc/grid-security/vomses"; StdOut: Your identity: /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=rquaglia/CN=758657/CN=Renato Quagliani/CN=proxy
Creating temporary proxy  Done
Contacting  voms2.cern.ch:15003 [/DC=ch/DC=cern/OU=computers/CN=voms2.cern.ch] "lhcb" Failed

Trying next server for lhcb.
Creating temporary proxy  Done
Contacting  voms.cern.ch:15003 [/DC=ch/DC=cern/OU=computers/CN=voms.cern.ch] "lhcb" Failed

Trying next server for lhcb.
Creating temporary proxy  Done
Contacting  lcg-voms2.cern.ch:15003 [/DC=ch/DC=cern/OU=computers/CN=lcg-voms2.cern.ch] "lhcb" Failed

Trying next server for lhcb.
Creating temporary proxy  Done
Contacting  voms2.cern.ch:15003 [/DC=ch/DC=cern/OU=computers/CN=voms2.cern.ch] "lhcb" Failed

Trying next server for lhcb.
Creating temporary proxy  Done
Contacting  lcg-voms2.cern.ch:15003 [/DC=ch/DC=cern/OU=computers/CN=lcg-voms2.cern.ch] "lhcb" Failed

Trying next server for lhcb.
Creating temporary proxy  Done
Contacting  lcg-voms.cern.ch:15003 [/DC=ch/DC=cern/OU=computers/CN=lcg-voms.cern.ch] "lhcb" Failed
; StdErr: .................................................................
Error: Error during SSL handshake:error:80066405:lib(128):verify_callback:outdated CRL found, revoking all certs till you get new CRL:sslutils.c:2115
outdated CRL found, revoking all certs till you get new CRL
Function: verify_callback
error:80066411:lib(128):verify_callback:certificate failed verify::sslutils.c:2318
        error =CRL has expired
        subject=/DC=ch/DC=cern/OU=computers/CN=voms2.cern.ch
        issuer =/DC=ch/DC=cern/CN=CERN Grid Certification Authority
certificate failed verify:
        error =CRL has expired
        subject=/DC=ch/DC=cern/OU=computers/CN=voms2.cern.ch
        issuer =/DC=ch/DC=cern/CN=CERN Grid Certification Authority
Function: verify_callback
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed:s3_clnt.c:1172
certificate verify failed
Function: SSL3_GET_SERVER_CERTIFICATE

..............................................
Error: Error during SSL handshake:error:80066405:lib(128):verify_callback:outdated CRL found, revoking all certs till you get new CRL:sslutils.c:2115
outdated CRL found, revoking all certs till you get new CRL
Function: verify_callback
error:80066411:lib(128):verify_callback:certificate failed verify::sslutils.c:2318
        error =CRL has expired
        subject=/DC=ch/DC=cern/OU=computers/CN=lcg-voms2.cern.ch
        issuer =/DC=ch/DC=cern/CN=CERN Grid Certification Authority
certificate failed verify:
        error =CRL has expired
        subject=/DC=ch/DC=cern/OU=computers/CN=lcg-voms2.cern.ch
        issuer =/DC=ch/DC=cern/CN=CERN Grid Certification Authority
Function: verify_callback
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed:s3_clnt.c:1172
certificate verify failed
Function: SSL3_GET_SERVER_CERTIFICATE

...............................
Error: Error during SSL handshake:error:80066405:lib(128):verify_callback:outdated CRL found, revoking all certs till you get new CRL:sslutils.c:2115
outdated CRL found, revoking all certs till you get new CRL
Function: verify_callback
error:80066411:lib(128):verify_callback:certificate failed verify::sslutils.c:2318
        error =CRL has expired
        subject=/DC=ch/DC=cern/OU=computers/CN=voms2.cern.ch
        issuer =/DC=ch/DC=cern/CN=CERN Grid Certification Authority
certificate failed verify:
        error =CRL has expired
        subject=/DC=ch/DC=cern/OU=computers/CN=voms2.cern.ch
        issuer =/DC=ch/DC=cern/CN=CERN Grid Certification Authority
Function: verify_callback
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed:s3_clnt.c:1172
certificate verify failed
Function: SSL3_GET_SERVER_CERTIFICATE

.......................................................
Error: Error during SSL handshake:error:80066405:lib(128):verify_callback:outdated CRL found, revoking all certs till you get new CRL:sslutils.c:2115
outdated CRL found, revoking all certs till you get new CRL
Function: verify_callback
error:80066411:lib(128):verify_callback:certificate failed verify::sslutils.c:2318
        error =CRL has expired
        subject=/DC=ch/DC=cern/OU=computers/CN=lcg-voms2.cern.ch
        issuer =/DC=ch/DC=cern/CN=CERN Grid Certification Authority
certificate failed verify:
        error =CRL has expired
        subject=/DC=ch/DC=cern/OU=computers/CN=lcg-voms2.cern.ch
        issuer =/DC=ch/DC=cern/CN=CERN Grid Certification Authority
Function: verify_callback
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed:s3_clnt.c:1172
certificate verify failed
Function: SSL3_GET_SERVER_CERTIFICATE

.................................................
None of the contacted servers for lhcb were capable
of returning a valid AC for the user.

 Are you sure you are properly registered in the VO? 
Could not add VOMS extensions to the proxy
Failed adding VOMS attribute: Failed to set VOMS attributes. Command: voms-proxy-init -cert "/tmp/x509up_u69481" -key "/tmp/x509up_u69481" -out "/tmp/rquaglia/tmp9dHr7i" -voms "lhcb:/lhcb/Role=user" -valid "23:54" -vomses "/afs/cern.ch/lhcb/software/releases/DIRAC/DIRAC_v6r12p33/etc/grid-security/vomses"; StdOut: Your identity: /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=rquaglia/CN=758657/CN=Renato Quagliani/CN=proxy
Creating temporary proxy  Done
Contacting  voms2.cern.ch:15003 [/DC=ch/DC=cern/OU=computers/CN=voms2.cern.ch] "lhcb" Failed

Trying next server for lhcb.
Creating temporary proxy  Done
Contacting  voms.cern.ch:15003 [/DC=ch/DC=cern/OU=computers/CN=voms.cern.ch] "lhcb" Failed

Trying next server for lhcb.
Creating temporary proxy  Done
Contacting  lcg-voms2.cern.ch:15003 [/DC=ch/DC=cern/OU=computers/CN=lcg-voms2.cern.ch] "lhcb" Failed

Trying next server for lhcb.
Creating temporary proxy  Done
Contacting  voms2.cern.ch:15003 [/DC=ch/DC=cern/OU=computers/CN=voms2.cern.ch] "lhcb" Failed

Trying next server for lhcb.
Creating temporary proxy  Done
Contacting  lcg-voms2.cern.ch:15003 [/DC=ch/DC=cern/OU=computers/CN=lcg-voms2.cern.ch] "lhcb" Failed

Trying next server for lhcb.
Creating temporary proxy  Done
Contacting  lcg-voms.cern.ch:15003 [/DC=ch/DC=cern/OU=computers/CN=lcg-voms.cern.ch] "lhcb" Failed
; StdErr: .................................................................
Error: Error during SSL handshake:error:80066405:lib(128):verify_callback:outdated CRL found, revoking all certs till you get new CRL:sslutils.c:2115
outdated CRL found, revoking all certs till you get new CRL
Function: verify_callback
error:80066411:lib(128):verify_callback:certificate failed verify::sslutils.c:2318
        error =CRL has expired
        subject=/DC=ch/DC=cern/OU=computers/CN=voms2.cern.ch
        issuer =/DC=ch/DC=cern/CN=CERN Grid Certification Authority
certificate failed verify:
        error =CRL has expired
        subject=/DC=ch/DC=cern/OU=computers/CN=voms2.cern.ch
        issuer =/DC=ch/DC=cern/CN=CERN Grid Certification Authority
Function: verify_callback
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed:s3_clnt.c:1172
certificate verify failed
Function: SSL3_GET_SERVER_CERTIFICATE

..............................................
Error: Error during SSL handshake:error:80066405:lib(128):verify_callback:outdated CRL found, revoking all certs till you get new CRL:sslutils.c:2115
outdated CRL found, revoking all certs till you get new CRL
Function: verify_callback
error:80066411:lib(128):verify_callback:certificate failed verify::sslutils.c:2318
        error =CRL has expired
        subject=/DC=ch/DC=cern/OU=computers/CN=lcg-voms2.cern.ch
        issuer =/DC=ch/DC=cern/CN=CERN Grid Certification Authority
certificate failed verify:
        error =CRL has expired
        subject=/DC=ch/DC=cern/OU=computers/CN=lcg-voms2.cern.ch
        issuer =/DC=ch/DC=cern/CN=CERN Grid Certification Authority
Function: verify_callback
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed:s3_clnt.c:1172
certificate verify failed
Function: SSL3_GET_SERVER_CERTIFICATE

**Comment by brucellino** [comment]
I'm getting the same error for the ops VO (same VOMS server) recently, but only on one site, where all of the other VOs  seem to be working. Watching this ticket...

**Comment by betatim** [comment]
Could you explain on which host you did this? The virtual machines we once
created for the starterkit should all be switched off by now and not
mentioned in the material anymore.

**Comment by brucellino** [comment]
Sorry, I may not have been clear in my message. This is happening on one of the Africa-Arabia-ROC sites in Johannesburg - not related to LHCb, just the same error 
We traced it down to a faulty CRL state file in /var/cache. See https://ggus.eu/?mode=ticket_info&ticket_id=119846

re-installing the CA cert for the CA that was giving the issue solved the problem.

**Comment by betatim** [comment]
I didn't see that the original issue was create such a long time ago sorry. Close this now?
