### ISSUE TITLE
Ganga application takes a list of options files

### ISSUE THREAD

**Issue by alexpearce** [lhcb/first-analysis-steps#107]
`j.application.optsfile` can take a list, allowing for modular options files.

``` python
>>> j.application.optsfile = ['davinci_mc_2010.py', 'ntuples.py']
```

Currently listed as a [single file](https://github.com/lhcb/first-analysis-steps/blob/9652eaf769fb4273afce7dc53059c39b52474a43/11-davinci-grid.md).

**Comment by cmarinbe** [comment]
In #211 we use a list but so far it only contains one element. We can just say they can add as many files as they want but to show it we would need to split the `DaVinci` configuration files. Maybe for next time? :slightly_smiling_face:

**Comment by alexpearce** [comment]
Yeah this is fine now. It's explicitly a list so it should be a hint. I usually teach this by splitting stuff up in to multiple files anyway.

**Comment by cmarinbe** [comment]
yep, I like it better too. Would be nice to have it in the lectures.
