### ISSUE TITLE
Ganga gridProxy.renew() error 

### ISSUE THREAD

**Issue by emanuelemichielin** [lhcb/first-analysis-steps#112]
When I try to run gridProxy.renew() on ganga I get this error:

gridProxy.renew()
Generating proxy... 
Enter Certificate password:
Could not add VOMS extensions to the proxy
Failed adding VOMS attribute: Failed to set VOMS attributes. Command: voms-proxy-init -cert "/tmp/x509up_u68762" -key "/tmp/x509up_u68762" -out "/tmp/emichiel/tmpAFDyaV" -voms "lhcb:/lhcb/Role=user" -valid "119:54" -vomses "/afs/cern.ch/lhcb/software/releases/DIRAC/DIRAC_v6r11p23/etc/grid-security/vomses"; StdOut: Your identity: /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=emichiel/CN=757773/CN=Emanuele Michielin/CN=proxy
Creating temporary proxy  Done
Contacting  voms.cern.ch:15003 [/DC=ch/DC=cern/OU=computers/CN=voms.cern.ch] "lhcb"; StdErr: .............................................. 

Solution: simply login in another lxplus node so ganga can recreate new /tmp/ directories

**Comment by alexpearce** [comment]
I guess this isn't true anymore. Running `gridProxy.renew()` in `lb-run Ganga ganga` (v602r2) works fine for me.
