### ISSUE TITLE
default root version too old

### ISSUE THREAD

**Issue by Svende** [lhcb/first-analysis-steps#113]
When opening just the default root on lxplus, the following warnings to pop up:

Warning in TStreamerInfo::BuildCheck: 
   The StreamerInfo for version 1 of class TObject read from the file DVntuple_new.root
   has a different checksum than the previously loaded StreamerInfo.
   Reading objects of type TObject from the file DVntuple_new.root 
   (and potentially other files) might not work correctly.
   Most likely the version number of the class was not properly
   updated [See ClassDef(TObject,1)].
Warning in TStreamerInfo::CompareContent: The following data member of
the on-file layout version 1 of class 'TObject' differs from 
the in-memory layout version 1:
   unsigned int fUniqueID; //
vs
   UInt_t fUniqueID; //
Warning in TStreamerInfo::CompareContent: The following data member of
the on-file layout version 1 of class 'TObject' differs from 
the in-memory layout version 1:
   unsigned int fBits; //

This is not really a problem but just anoying. This can be changed when using the root version which is compatible with DaVinci, like lb-run DaVinci v36r6 root -l

**Comment by mfiore5487** [comment]
You can also write SetupProject ROOT in order to set the latest ROOT version as the version you are going to use.

**Comment by lbel** [comment]
Wasn't SetupProject to be eventually removed completely? Not sure that's something we want to teach to new people...

That aside, SetupProject ROOT has historically been problematic...

**Comment by benedettosiddi** [comment]
You could try to set up another root version, the instructions are in this page:
https://root.cern.ch/drupal/content/starting-root

**Comment by apuignav** [comment]
Why has it been problematic?

**Comment by lbel** [comment]
I've seen a lot of people run into problems when using it. Never used it myself though, always used root through SetupDaVinci or similar. 
`lb-run ROOT root` seems to work fine though!

**Comment by apuignav** [comment]
I think `lb-run ROOT` just defaults to SetupProject ROOT

``` output
apuignav@lxplus0042:~$ lb-run ROOT $SHELL
WARNING:root:trying old SetupProject (cannot find project ROOT prod for
x86_64-slc6-gcc48-opt in ['/afs/cern.ch/user/a/apuignav/cmtuser', '/afs/
cern.ch/lhcb/software/releases/LBSCRIPTS/LBSCRIPTS_v8r3p1/LbRelease/data/DataPkgEnvs',
'/afs/
cern.ch/lhcb/software/releases/LBSCRIPTS/LBSCRIPTS_v8r3p1/LbUtils/cmake',
'/afs/cern.ch/user/a/apuignav/cmtuser', '/afs/cern.ch/lhcb/software/releases',
'/afs/cern.ch/sw/Gaudi/releases', '/afs/cern.ch/sw/lcg/releases', '/afs/
cern.ch/sw/lcg/app/releases', '/afs/cern.ch/lhcb/software/releases', '/afs/
cern.ch/sw/Gaudi/releases', '/afs/cern.ch/sw/lcg/releases', '/afs/
cern.ch/sw/lcg/app/releases'])
ALWAYS:SetupProject:Configuring LCGCMT 76root6 from /afs/
cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_76root6
Configuring LCGCMT 76root6 from /afs/
cern.ch/sw/lcg/releases/LCGCMT/LCGCMT_76root6
```

**Comment by alexpearce** [comment]
@apuignav is right: we should consider the default to be `lb-run ROOT root`.
