### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by kdungs** [lhcb/first-analysis-steps#115]
When I google "LHCb Starterkit" I don't find the GH pages of this immediately.
Suggestions?

**Comment by ibab** [comment]
It should get ranked higher if we give it some time.
It's the third options for me after Indico and Tim's repo.

**Comment by kdungs** [comment]
Yes but the title is also not very intuitive.

**Comment by kdungs** [comment]
Also do you have personalised search activated? For me it doesn't show up on page 1 at all.

**Comment by betatim** [comment]
What do you mean with the title not being intuitive?

I think we need to create more public links on non spammy sites (ie not
twitter, FB) if we want google to find us. This also relates to #69 where
we want to introduce analytics to the webpage

**Comment by alexpearce** [comment]
I get it as the first link 😄 I'll close for now, do leave a comment if you see something different (particularly if it's not on the first page).
