### ISSUE TITLE
Etherpad Links

### ISSUE THREAD

**Issue by benedettosiddi** [lhcb/first-analysis-steps#119]
I could be possibile to have al the ether pad stuff merged in a single place?

**Comment by kdungs** [comment]
The etherpads are usually very dynamic and depend a lot on what happens during the day. Since we want to re-use the material for the next iteration(s) it would be good to keep them separate.

**Comment by betatim** [comment]
Persisting the links somehow would be useful though. We could add them (vaguely by day) to the indico agenda?

Next time we should be more organised and create the agenda ahead of time and directly link them.

**Comment by betatim** [comment]
I've added these three etherpads:
- https://etherpad.mozilla.org/ZJC3cSKeby (day one and two)
- https://etherpad.mozilla.org/XQOPOxiHDi (days three and four for the building 104 room)
- https://etherpad.mozilla.org/OZ9cGUzSKD (days three and four for the building 2 room)

to the indico agenda as "Minutes".

Where there other etherpads?

**Comment by elgicse** [comment]
Yes: https://etherpad.mozilla.org/nqOTbdJEbk (days one and two, building 104)

**Comment by alexpearce** [comment]
Relevant for an old workshop.
