### ISSUE TITLE
DecayTreeFitter and DecayTreeTuple

### ISSUE THREAD

**Issue by FedericaLionetto** [lhcb/first-analysis-steps#133]
During the workshop we said that, whenever we use DecayTreeFitter, some variables in the ntuples are going to be affected (for example, the IPCHI2_OWNPV of the head particle).
I just checked in my ntuples and it seems that the variables that were already there are not affected at all. I have new variables, but the old ones are still the same as before.
So now I'm rather puzzled about that...am I missing anything?
Below you find the related code.

```
tuple.B.addTupleTool('TupleToolDecayTreeFitter/B_DTF_PVandJpsi')
tuple.B.B_DTF_PVandJpsi.Verbose = True
tuple.B.B_DTF_PVandJpsi.constrainToOriginVertex = True
tuple.B.B_DTF_PVandJpsi.daughtersToConstrain = ['J/psi(1S)']
```

**Comment by apuignav** [comment]
I think the `B_ IPCHI2_OWNPV` should not be affected, since it's filled without the `DecayTreeFitter` info.  In principle the tool does not affect the variables filled with other tools.

**Comment by FedericaLionetto** [comment]
This is also what I understood...but then this sentence (from the DecayTreeFitter lesson) might be confusing:

"It is important to be aware what assumptions you bake into your ntuple. For example, after you require the vertex constraint you can't use the IP_CHI2_OWNPV anymore, since the particle you are looking at is forced to point to the PV. Which constraints make most sense for you depends on the questions you want to ask in your analysis."

It might give the idea the variable cannot be used because it changed when adding the DecayTreeFitter tool, which is not actually the case.
So maybe I would add more details here and/or rephrase it...what do you think?

**Comment by alexpearce** [comment]
Indeed, the branches that aren't created by `TupleToolDecayTreeFitter` _are not_ changed.

I agree that the sentence should be rephrased.

**Comment by apuignav** [comment]
Yes, you have to be careful because physics-wise you cannot use the `IP_CHI2_OWNPV` if your particle has been forced to have it equal to 0. It's not a code issue, it's a physics issue, I think rephrasing is needed.

**Comment by alexpearce** [comment]
I actually don't know if there's a problem using a PV-constrained `DTF_M` but the usual `IPCHI2_OWNPV` together, say in a 2D fit. They're computed using different assumptions, but I suppose that doesn't preclude using them simultaneously.

**Comment by FedericaLionetto** [comment]
I think it's fine if we rephrase it so that it's clear how the tool works. We might even split the discussion in two:
- from the computing point of view (old variables stay the same, new variables are created, one set per DecayTreeFitter instance)
- from the physics point of view (analysis and whether it makes sense or not to use IPCHI2_OWNPV after the constraints have been applied)

**Comment by alexpearce** [comment]
That's a good idea. I would focus less and the second point, and the physics issues are almost always “depends on what you want to do”. I'm happy with just “talk to your supervisor/working group”.

**Comment by apuignav** [comment]
Agree with @apearce. Can we haz PR?

On Wed, Jul 8, 2015 at 3:08 PM, Alex Pearce notifications@github.com
wrote:

> That's a good idea. I would focus less and the second point, and the
> physics issues are almost always “depends on what you want to do”. I'm
> happy with just “talk to your supervisor/working group”.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/lhcb/first-analysis-steps/issues/133#issuecomment-119573290
> .

## 

Dr. Albert Puig Navarro
Laboratoire de Physique des Hautes Energies
Ecole Polytechnique Fédérale de Lausanne (EPFL)
BSP 614.4 (Cubotron UNIL) CH-1015 Lausanne
EPFL Phone: 021 6939808
CERN Phone: 72518

**Comment by FedericaLionetto** [comment]
I'm lost with PR, sorry :P

**Comment by apuignav** [comment]
Pull request :-)

On Wed, Jul 8, 2015 at 3:12 PM, FedericaLionetto notifications@github.com
wrote:

> I'm lost with PR, sorry :P
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/lhcb/first-analysis-steps/issues/133#issuecomment-119574080
> .

## 

Dr. Albert Puig Navarro
Laboratoire de Physique des Hautes Energies
Ecole Polytechnique Fédérale de Lausanne (EPFL)
BSP 614.4 (Cubotron UNIL) CH-1015 Lausanne
EPFL Phone: 021 6939808
CERN Phone: 72518

**Comment by FedericaLionetto** [comment]
Do you want me to edit the text or are you going to do it?

**Comment by apuignav** [comment]
Please do.

On Wed, Jul 8, 2015 at 3:26 PM, FedericaLionetto notifications@github.com
wrote:

> Do you want me to edit the text or are you going to do it?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/lhcb/first-analysis-steps/issues/133#issuecomment-119577291
> .

## 

Dr. Albert Puig Navarro
Laboratoire de Physique des Hautes Energies
Ecole Polytechnique Fédérale de Lausanne (EPFL)
BSP 614.4 (Cubotron UNIL) CH-1015 Lausanne
EPFL Phone: 021 6939808
CERN Phone: 72518

**Comment by betatim** [comment]
This is being dealt with in #134
