### ISSUE TITLE
Fun with LoKi functors

### ISSUE THREAD

**Issue by betatim** [lhcb/first-analysis-steps#14]
Move the complicated stuff from #11 here. Then go even deeper?

How to look at the code of a LoKi functor, how to find more LoKi functors, how to figure out what they are doing, why do we need these "adaptor" functions, how to edit the code of a functor and use it.

**Comment by apuignav** [comment]
Do we want to go deeper? I can write a small lesson on how to write a functor, but maybe it's too much and we should stick with #48.

**Comment by betatim** [comment]
I will close this for now
