### ISSUE TITLE
The ganga magic function in the ganga interactive mode has been removed in newer versions.

### ISSUE THREAD

**Issue by KonstantinSchubert** [lhcb/first-analysis-steps#151]
Doing `ganga job.py` inside the python console does give a syntax error now.

Accordingly, this line would need to be updated (but how?):
https://github.com/lhcb/first-analysis-steps/blame/master/10-davinci-grid.md#L73

Here is the associated JIRA ticket: https://its.cern.ch/jira/browse/GANGA-2005

**Comment by ttekampe** [comment]
I think we can close that one. For me `%ganga my_script.py` works. Maybe they fixed it.
Otherwise we can switch to `execfile('my_script.py')`

**Comment by alexpearce** [comment]
👍
