### ISSUE TITLE
Update lesson filenames to match order

### ISSUE THREAD

**Issue by betatim** [lhcb/first-analysis-steps#153]
See discussion in #152. I like @alexpearce's suggestion of getting rid of the numbers in the filenames. Only downside I can see is that locating the right file to edit in the terminal gets a bit harder.

**Comment by alexpearce** [comment]
In [lhcb/second-analysis-steps](https://github.com/lhcb/second-analysis-steps) a few files all begin with `01-`. I think this is done because the template requires the filenames to begin with a number.

**Comment by eduardo-rodrigues** [comment]
Made irrelevant after 6 years of developments and changes.
