### ISSUE TITLE
Add link to starterkit tutorials in outdated twikis

### ISSUE THREAD

**Issue by cmarinbe** [lhcb/first-analysis-steps#154]
The starterkit tutorial is great! But there are still many LHCb twiki pages with outdates and non-working examples that can be easily found when asking google for help with LHCb software. You can spend many hours trying to understand why the examples given in that pages don't work for you.. while they just don't work anymore.
I think it may be worth it to add a link to this tutorial in those twikis.

**Comment by betatim** [comment]
Good idea. I thought we had added it in some places, but struggling to find
it now Which supports your point.

Do you have some suggestions where it would be good to add it so that
people find it?

**Comment by cmarinbe** [comment]
I've a bunch of them saved in my browser :) I need to go through them and see if it has already been added or if it's relevant there. Will let you know when I add it somewhere.

I was thinking to add the direct link to the relevant lesson. For instance, to a tutorial of how to run on ganga, just add the link of that part of the starterkit lessons. Is this the way you have been doing it so far?

**Comment by betatim** [comment]
IIRC (if I recall correctly) we added a link to the whole of `first-analysis-steps` to the [software tutorials](https://twiki.cern.ch/twiki/bin/view/LHCb/LHCbSoftwareTutorials) page but I can't find it there.

I think deep linking to the individual starterkit pages will set us up for maintenance hell, as they change sometimes. So I think we are better off linking to the front page of `first-analysis-steps` as a whole and relying on people finding their way around via the index. Probably also means we shouldn't insert links in the middle of a ganga tutorial.

**Comment by cmarinbe** [comment]
Ok, so maybe that's the place to start with. Could it be that you added it there and someone removed it afterwards? Could we ask the people who maintains that pages to add and keep it there? (if you haven't already)

I see your point, broken links in a tutorial is the last we want (at least for me it's really annoying and creates distrust), so fine with adding the front page. The index is indeed quite obvious :)

**Comment by kdungs** [comment]
Push

**Comment by betatim** [comment]
@cmarinbe do you want to add the link to the software tutorial twiki?

**Comment by cmarinbe** [comment]
Done! See the [software tutorials twiki](https://twiki.cern.ch/twiki/bin/view/LHCb/LHCbSoftwareTutorials).
The description could probably be improved, so suggestions are welcome :)

**Comment by betatim** [comment]
Nice! We send :cake: and congrats on your first (of hopefully many) contributions to the starterkit!

**Comment by kdungs** [comment]
:beers:

**Comment by cmarinbe** [comment]
Thank you, guys! :v: :smile: 

I've talked to Marco Cattaneo about this. He found it a good idea and suggested removing the links to old tutorials that are now superseded by the Starterkit. I think this is a good idea to avoid confusion to newcomers. But someone needs to go through all the tutorials to check the material covered there. I will not have time before Christmas for doing this.

Moreover, he asked whether we should also put a visible link in the [LHCb computing home page](http://lhcb-comp.web.cern.ch/lhcb-comp/) and/or the [LHCb computing Twiki](https://twiki.cern.ch/twiki/bin/view/LHCb/LHCbComputing). From the first one, one can already get to the software tutorials twiki, but a more visible link would be useful. I would suggest linking the Starterkit directly here, next to the tutorials link, with a :new: icon if possible. In the computing Twiki, there's already a direct link to the Starterkit tutorial in the Software training section (maybe this is what @betatim remember adding?), which I think it's enough.

**Comment by saschastahl** [comment]
Yes, I think it should not take more than two clicks from the lhcb start page to get to the StarterKit.
So I vote for the LHCb computing home page (and the LHCb computing Twiki).

**Comment by cmarinbe** [comment]
Marco has added it in the Hot News section, so just two clicks from the lhcb home page and clearly visible :)

He asked for the dates and registration link for the next tutorial but afaik this is not yet available. Is that right @kdungs @betatim? Once we have it, we should write him with this information and he will also add it to the hot news.

**Comment by kdungs** [comment]
I will talk to Carnita this afternoon on whether there are any news concerning rooms.

**Comment by kdungs** [comment]
Btw. it's great the the tutorials are linked. I was just wondering if it wouldn't be better to use the common overview page instead? That is http://lhcb.github.io/starterkit/

**Comment by saschastahl** [comment]
This would take too many clicks to get to the material which I am interested in if I go to LHCb computing.
One could ask management and secretariat to put the link you mention to this page http://lhcb.web.cern.ch/lhcb/lhcb_page/collaboration/newcomers/default.html .

**Comment by betatim** [comment]
The original point was to discuss linking directly to the material from inside the twiki. We should also discuss linking to the front page of the starterkit and from where, but it should be a new issue: #161
