### ISSUE TITLE
Create a separate page that lists the contributors for each year

### ISSUE THREAD

**Issue by ibab** [lhcb/first-analysis-steps#155]
Makes it easier to find out who helped and instructed and gives everyone a fuzzy feeling

**Comment by kdungs** [comment]
Does this belong into https://github.com/lhcb/starterkit?

**Comment by ibab** [comment]
Maybe or maybe not, as we can do this on a per-starterkit basis. (Meaning separate for the first and second analysis steps)

**Comment by betatim** [comment]
I think it belongs in https://github.com/lhcb/starterkit that should
contain a webpage for each "instance" of the starterkit event. Listing who
helped, what the material was in that event etc

**Comment by alexpearce** [comment]
Opened as lhcb/starterkit#30.
