### ISSUE TITLE
Setup issues

### ISSUE THREAD

**Issue by henryiii** [lhcb/first-analysis-steps#173]
When I was first getting setup, I ran into a few issues. For the mentioned `cern-convert.sh` for setting up the cert, the script was not in the path, so I had to use the manual method linked to in the alternate methods.

The default shell is now Bash, so that comment can be changed or removed.

I can make a PR to address either or both of these issues if they are valid.

**Comment by alexpearce** [comment]
I'm very happy to hear that the default isn't `tcsh` anymore! 🎉 

Did you mean `cert-convert.sh`? It should be available to all users, it is for me and I don't do any special LHCb setup.

**Comment by henryiii** [comment]
I think I was typing cern-convert. :#)

Added the bash comment.
