### ISSUE TITLE
File number

### ISSUE THREAD

**Issue by henryiii** [lhcb/first-analysis-steps#175]
The file used seems to change from `00035742_00000001_1.allstreams.dst` to `00035742_00000002_1.allstreams.dst` randomly. If using the fast download of one file (the 1 file), the other file (2) does not work. Would it be better to use just the first file when only one file is used?

**Comment by alexpearce** [comment]
Yes, we should be consistent with the file we use.

**Comment by ibab** [comment]
This has already been fixed by #177
