### ISSUE TITLE
lhcb-proxy-init is broken

### ISSUE THREAD

**Issue by KonstantinSchubert** [lhcb/first-analysis-steps#180]
The instructions here 

https://github.com/lhcb/first-analysis-steps/blob/master/04-files-from-grid.md

regarding the call of `lhcb-proxy-init` are outdated because the command does not longer work. 
I posted a question about [this on LHCbQA](https://lhcbqa.web.cern.ch/lhcbqa/416/lhcb_proxy_init-gives-problem-lhcbdirac-environment-lxplus). I am not sure about the background on this, thus I am hesitant to propose a fix.

**Comment by alexpearce** [comment]
`lhcb-proxy-init` works for me today. I don't remember seeing a specific thread saying "it's OK to use again now", but maybe that's the case?

**Comment by alexpearce** [comment]
The command is no longer broken.
