### ISSUE TITLE
Explain what an NTuple is

### ISSUE THREAD

**Issue by ibab** [lhcb/first-analysis-steps#195]
The lesson "Running a minimal DaVinci job locally" says that we're going to create an NTuple, but doesn't explain what it is:
 > it's useful to store the information on the selected particles inside an ntuple

Would be nice to have a box defining it

**Comment by eduardo-rodrigues** [comment]
As for many words we can simply link to the LHCb glossary we have since a while, see https://lhcb.github.io/glossary/glossary/N.html for a definition of ntuple. I'm sure a link will be made if people stumble over the word. Closing.
