### ISSUE TITLE
Lesson "More on Ganga" doesn't exist anymore

### ISSUE THREAD

**Issue by cmarinbe** [lhcb/first-analysis-steps#210]
see: https://lhcb.github.io/first-analysis-steps/ganga-data.md

**Comment by alexpearce** [comment]
The extension in the link in [`index.md`](https://github.com/lhcb/first-analysis-steps/blob/2240684bd430a0fe584c57b0e416a7df5b7663bc/index.md) needs changing from `.md` to `.html`.

**Comment by cmarinbe** [comment]
Yep, I realised just yesterday, I commented on the commit. Maybe we can
close this one.

El dia 01/12/2016 11.14, "Alex Pearce" <notifications@github.com> va
escriure:

**Comment by alexpearce** [comment]
@amoedden feel free to submit your PR as well!
