### ISSUE TITLE
Setting up project fails

### ISSUE THREAD

**Issue by rob-c** [lhcb/first-analysis-steps#233]
Hi all,

I'm a bit new to some of the tools here so apologies if this is just my ignorance.

I have tired to setup this project. I've done a `git clone` from a private fork and followed this with `pip install -r requirements.txt`

I then cannot get the make preview to build, I keep getting:

```
# The --mathjax flag will change and $ to \(\) and \[\],
# which our KaTeX installation will auto-convert to LaTeX
pandoc -s -t html \
--template=_layouts/page \
--filter=tools/filters/blockquote2div.py \
--filter=tools/filters/id4glossary.py \
--mathjax \
-Vheader="$(cat _includes/header.html)" -Vbanner="$(cat _includes/banner.html)" -Vfooter="$(cat _includes/footer.html)" -Vjavascript="$(cat _includes/javascript.html)" \
-o _site/add-tupletools.html add-tupletools.md
pandoc: Error running filter tools/filters/blockquote2div.py
tools/filters/blockquote2div.py not found in path
make: *** [_site/add-tupletools.html] Error 83
```

Is there some magic I need to do to get this to work. I'm running this from the root account on a CentOS 7 VM.

I'll drop down to a user account and try `pip install --user` and see where it gets me, but if anyone can suggest a quick fix much appreciated :)

Thanks in advance,

Rob

**Comment by alexpearce** [comment]
I've just run these steps and things worked:

```shell
$ git clone git@github.com:lhcb/first-analysis-steps.git
$ cd first-analysis-steps
$ virtualenv env
$ source env/bin/activate
$ pip install -r requirements.txt
$ make preview
```

Making the virtualenv should be optional.

Are you running `make preview` in the root of the repository?

**Comment by rob-c** [comment]
@alexpearce Thanks this solved it :+1: 

I'm not too surprised that `virtualenv` fixed this, I should have remembered to give it a try.
(for posterity yes I was just running make preview in the root of the build which is why this confused me so, and adding `./` to the Makefile didn't seem to help :/ )

OK, I'll try and get to work with what I was hoping to document,
(how to setup LHCb stuff at CERN without AFS)

Thanks again!

**Comment by alexpearce** [comment]
Glad to hear it! And very happy to hear your writing a lesson on that topic 😄
