### ISSUE TITLE
Move to a gh orga

### ISSUE THREAD

**Issue by betatim** [lhcb/first-analysis-steps#29]
We should move this repo to somewhere that makes it clear that this is a group effort and that everyone is welcome to contribute. Hopefully this way we can encourage others to help create a few more of these collections of lessons on advanced topics like ML or RooFit or Brunel. (There is a lot of demand for that.)

There is a LHCb orga on github, it seems inactive and I have not been able to work out who controls it. We should try again and/or ask gh to put us in touch?

Part of this we should create an open egroup called `lhcb-starterkit@cern.ch` to which anyone can subscribe and list that as the contact point.

**Comment by alexpearce** [comment]
Doubleplusgood on this. Could send an email to `lhcb-core-soft`? One of those people might have reserved it (I know some of them have tried GH).

**Comment by apuignav** [comment]
Can we ask GH to put us in touch with whoever owns it? If they don't reply
and we cannot find the person we can always report abuse and get the ball
rolling...

On Fri, May 22, 2015 at 9:19 AM, Alex Pearce notifications@github.com
wrote:

> Doubleplusgood on this. Could send an email to lhcb-core-soft? One of
> those people might have reserved it (I know some of them have tried GH).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/betatim/lhcb-first-analysis-steps/issues/29#issuecomment-104545047
> .

## 

Dr. Albert Puig Navarro
Laboratoire de Physique des Hautes Energies
Ecole Polytechnique Fédérale de Lausanne (EPFL)
BSP 614.4 (Cubotron UNIL) CH-1015 Lausanne
EPFL Phone: 021 6939808
CERN Phone: 72518

**Comment by betatim** [comment]
I have created `lhcb-starterkit@cern.ch`, some of you are already subscribed but otherwise add yourself!

**Comment by betatim** [comment]
Email to `lhcb-core-soft` sent.

**Comment by kdungs** [comment]
@sbinet works on @lhcb-org.
Who owns the @lhcb account I don't know.

**Comment by ibab** [comment]
@betatim , can you send a request to Github asking if they can do something about the `lhcb` org?

**Comment by betatim** [comment]
From the relies on `lhcb-core-soft` I deduce that we do not know who
controls the LHCb orga. I will get in touch with gh.

Predictably the question of `gitlab.cern.ch` vs 'github.com/LHCb`was
raised. We should form a collective opinion here, then transmit that to
`core-soft`.

I am :-1: on moving to gitlab, as I don't see any benefits and just a lot
of work.

**Comment by apuignav** [comment]
+1 on the gitlab thing. Being a regular gitlab user (we have one at EPFL
that I admin) I see some very nice features lacking.

On Fri, May 22, 2015 at 10:17 AM, Tim Head notifications@github.com wrote:

> From the relies on `lhcb-core-soft` I deduce that we do not know who
> controls the LHCb orga. I will get in touch with gh.
> 
> Predictably the question of `gitlab.cern.ch` vs 'github.com/LHCb`
> <http://github.com/LHCb> was
> raised. We should form a collective opinion here, then transmit that to
> `core-soft`.
> 
> I am :-1: on moving to gitlab, as I don't see any benefits and just a lot
> of work.
> 
> On Fri, May 22, 2015 at 9:56 AM Igor Babuschkin notifications@github.com
> wrote:
> 
> > Tim, can you send a request to Github asking if they can do something
> > about the lhcb org?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/betatim/lhcb-first-analysis-steps/issues/29#issuecomment-104556593
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/betatim/lhcb-first-analysis-steps/issues/29#issuecomment-104561341
> .

## 

Dr. Albert Puig Navarro
Laboratoire de Physique des Hautes Energies
Ecole Polytechnique Fédérale de Lausanne (EPFL)
BSP 614.4 (Cubotron UNIL) CH-1015 Lausanne
EPFL Phone: 021 6939808
CERN Phone: 72518

**Comment by kdungs** [comment]
I am also +1 on the -1 on gitlab. We already have GitHub in place, it works, we want the stuff to be public, we want to integrate it with external services, we use gh-pages, and most importantly we don't have time for a migration. Did I miss anything?

**Comment by ibab** [comment]
I agree with @kdungs
