### ISSUE TITLE
Automatic generation of gh-pages

### ISSUE THREAD

**Issue by kdungs** [lhcb/first-analysis-steps#30]
Use [Travis](travis-ci.org) or something similar to automatically compile the markdown to html and then push to `gh-pages`. Use `master` again for upstream development.

**Comment by ibab** [comment]
I've forked the repo and will report back once I've come up with a way to set things up.

**Comment by alexpearce** [comment]
Seeing as this will use Travis, we could also run `make check` as ‘tests’. Gives a few warnings atm:

```
python tools/check.py .
ERROR: Missing file discussion.md.
ERROR: Missing file instructors.md.
ERROR: Missing file motivation.md.
ERROR: Missing file reference.md.
ERROR: In ./03-bookkeeping.md: Could not find the linked asset file data/MC_2012_27163003_Beam4000GeV2012MagDownNu2.5Pythia8_Sim08e_Digi13_Trig0x409f0045_Reco
14a_Stripping20NoPrescalingFlagged_ALLSTREAMS.DST in ./data/MC_2012_27163003_Beam4000GeV2012MagDownNu2.5Pythia8_Sim08e_Digi13_Trig0x409f0045_Reco14a_Stripping
20NoPrescalingFlagged_ALLSTREAMS.DST. If this is a URL, it must be prefixed with http(s):// or ftp://.
ERROR: In ./05-files-from-grid.md: Found callout box with unrecognized style 'prereq'
ERROR: In ./09-minimal-dv-job.md: Could not find the linked asset file data/MC_2012_27163003_Beam4000GeV2012MagDownNu2.5Pythia8_Sim08e_Digi13_Trig0x409f0045_R
eco14a_Stripping20NoPrescalingFlagged_ALLSTREAMS.DST in ./data/MC_2012_27163003_Beam4000GeV2012MagDownNu2.5Pythia8_Sim08e_Digi13_Trig0x409f0045_Reco14a_Stripp
ing20NoPrescalingFlagged_ALLSTREAMS.DST. If this is a URL, it must be prefixed with http(s):// or ftp://.
ERROR: In ./14-rerun-stripping.md: Could not find the linked asset file ./code/09-ntuple_options.py in ././code/09-ntuple_options.py. If this is a URL, it mus
t be prefixed with http(s):// or ftp://.
ERROR: In ./index.md: The linked page 03-bookkeeping.html exists, but the link text 'Find the dataset in the Bookkeeping' does not match the (sub)title of tha
t page, 'Finding data to process'.
ERROR: In ./index.md: The linked page 05-interactive-dst.html exists, but the link text 'Interactive look inside a DST with python' does not match the (sub)ti
tle of that page, 'Interactively exploring a DST'.
ERROR: In ./index.md: The linked page 14-rerun-stripping.html exists, but the link text 'Switch to a new stripping (20 -> 21) for one line in MC' does not mat
ch the (sub)title of that page, 'Running a specific stripping version on a DST'.
ERROR: In ./index.md: The document links to motivation.html, but could not find the expected markdown file ./motivation.md
ERROR: In ./index.md: The document links to reference.html, but could not find the expected markdown file ./reference.md
ERROR: In ./index.md: The document links to discussion.html, but could not find the expected markdown file ./discussion.md
ERROR: In ./index.md: The document links to instructors.html, but could not find the expected markdown file ./instructors.md
WARNING: Some errors were encountered during validation. See log for details.
make: *** [check] Error 1
```

**Comment by kdungs** [comment]
Yes, excellent. Tests should be used.

**Comment by ibab** [comment]
Woa, that's cool

**Comment by betatim** [comment]
:+1: on auto builds. Maybe we should quiz the @swcarpentry `lesson-template` maintainers why they didn't switch to using travis (or if we can contribute that back if it works nicely)

**Comment by ibab** [comment]
I'm close to getting it working, the main problem is that the pandoc version on travis is too old and doesn't support the `--filter` option.

**Comment by ibab** [comment]
Okay, it's working at https://github.com/ibab/lhcb-first-analysis-steps.
The travis builds can be inspected here: https://travis-ci.org/ibab/lhcb-first-analysis-steps/builds/63633990.
The finished page is visible at http://ibab.github.io/lhcb-first-analysis-steps/.

You can test it by committing to the master branch (Only `master` is compiled for now).
If everyone is okay with using this, we can think about adding it to the actual repo (maybe when we switch to the lhcb org?).

**Comment by kdungs** [comment]
Igor, you're awesome! Will test it immediately.

**Comment by kdungs** [comment]
Sorry, hit the wrong button :D

**Comment by kdungs** [comment]
Works. As soon as we have the repo over at the org, we can integrate it.

**Comment by betatim** [comment]
So what changes in our workflow?
- we merge things into `master` instead of `gh-pages`
- ...??
- profit!

**Comment by kdungs** [comment]
> So what changes in our workflow?
> - we merge things into master instead of gh-pages
- Travis picks up the changes, builds the site, pushes the result to gh-pages (GitHub picks up the changes and displays them on the website), and runs the tests

> - profit!

**Comment by ibab** [comment]
Note that `make preview` now places stuff in `_site` instead of the main directory.
We will have to set `master` as our default branch.
The rest should stay the same.

**Comment by kdungs** [comment]
Merci, Igor!

**Comment by betatim** [comment]
:beers: :fireworks: :cake:
