### ISSUE TITLE
General introduction to Gaudi/DaVinci

### ISSUE THREAD

**Issue by betatim** [lhcb/first-analysis-steps#4]
5min summary of the buzzwords one needs to know to make a little sense of what happens in DV.

(as in not "Gaudi is an object orientated framework with tools, algorithms, public tools, ...")

**Comment by ibab** [comment]
Some more general questions I would like to see answered as part of the workshop (not necessarily this lesson):
- Which problems specific to HEP/LHCb is Gaudi designed to solve?
- What are Algorithms and Tools?
- What is an option file?
- What is the relationship between DaVinci and Gaudi?
- What are `lb-run` and `lb-dev`?
- How do I run Gaudi using my option file?
- How can I browse the code/documentation of the LHCb software?
- How can I check out an LHCb package?

**Comment by kdungs** [comment]
I can write something about those points. Might have to leave some holes but I'll see what I can do.

**Comment by kdungs** [comment]
First steps here: https://github.com/lhcb/first-analysis-steps/tree/content/gaudi-general

Need to set up my Mac now, will continue later. Feel free to add stuff (especially the first three points...) in the meantime.

**Comment by betatim** [comment]
Woah, why not fork and do your stuff there! I thought we were discouraging people doing stuff in the repo :-/

**Comment by kdungs** [comment]
No you misunderstood. Discourage doing stuff on master.

**Comment by betatim** [comment]
That is clear, to me the extra level of forking is still a good idea and
means none of us are special.

**Comment by kdungs** [comment]
Ah I hadn't gone through the 30 notifications yet... I see you already merged contribution guidelines, then of course I will do as they say.

**Comment by kdungs** [comment]
@ibab: 

> - How can I check out an LHCb package?

Do you mean "(svn) checkout" or "check out what's inside"?

**Comment by ibab** [comment]
I mean a quick tutorial on how to use `getpack` and maybe how it translates to `svn`.

**Comment by kdungs** [comment]
What is a typical project one `getpack`s when working with DaVinci?

**Comment by alexpearce** [comment]
[`Phys/StrippingSelections`](https://svnweb.cern.ch/trac/lhcb/browser/Stripping/trunk/Phys/StrippingSelections) maybe?

**Comment by ibab** [comment]
Maybe `Phys/DecayTreeTuple`

**Comment by alexpearce** [comment]
Closed by #57.
