### ISSUE TITLE
CombineParticles/Selection framework lesson

### ISSUE THREAD

**Issue by apuignav** [lhcb/first-analysis-steps#46]
Should we have a lesson on CombineParticles/FilterDesktop, etc?

**Comment by seneubert** [comment]
I will include a very basic bit on selections for the changeing of mass hypothesis

**Comment by betatim** [comment]
You need to do selection framework stuff to change mass hypos?

**Comment by apuignav** [comment]
I don't think so, I would do a separate lesson, when I finish LoKi functors
I can do it.

**Comment by betatim** [comment]
It would make sense to have a small explanation on what it is and how stripping lines come into existence. Writing a stripping line isn't a beginner task though, so some part of me is thinking "beyond the scope of this tutorial". Maybe it fits well in the "general outline about stripping" part? Was actually wondering what to put there.

**Comment by seneubert** [comment]
Yes you need a selection to do change the mass hypo. I'll open a new issue to discuss the solution

**Comment by alexpearce** [comment]
Closed by #71.
