### ISSUE TITLE
Broken link in index.md

### ISSUE THREAD

**Issue by seneubert** [lhcb/first-analysis-steps#47]
The link to the prerequisite page in index.md does not work

**Comment by seneubert** [comment]
Actually none of these links work. What am I doing wrong?

**Comment by betatim** [comment]
The links only work in the [rendered version](http://lhcb.github.io/first-analysis-steps) unfortunately.

Reason: you write 00-prereqs.html as the target in the `.md` but that page will only exists in the rendered version. One downside of not having the `html` checked into the repo I guess
