### ISSUE TITLE
Detection of end of file doesn't work in 05-interactive-dst.md

### ISSUE THREAD

**Issue by apuignav** [lhcb/first-analysis-steps#51]
While this usually works, the lines

``` python

if not evt["/Event/DAQ/RawEvent"]:
    print "Reached end of input files"
    break

```

in `05-interactive-dst.md` actually don't work in this file because `/Event/DAQ/RawEvent` doesn't exist. I don't know why, I have been using for years.

**Comment by betatim** [comment]
How about using `evt['/Event/Rec/Header']`? This should exist in simulation and data. It will break if you use something before `Brunel` so I will add a comment stating that.
