### ISSUE TITLE
Decide if we should do a lesson on decfiles

### ISSUE THREAD

**Issue by ibab** [lhcb/first-analysis-steps#60]
Modifying or writing a decfile from scratch is something that many PhD students might have to do early on. Do we want to create a lesson for this?

**Comment by apuignav** [comment]
I think this may be too specific/advanced, but if someone has the time to
write it, why not?

I believe it shouldn't be a priority, though.

**Comment by seneubert** [comment]
what @apuignav said

**Comment by saschastahl** [comment]
I haven't looked at a decfile in 6 years.

**Comment by alexpearce** [comment]
:laughing: lucky!

I've had to deal with them a few times. There are a lot of examples, but there's so much you can do with them and so little documentation that it might be a bit of a minefield.

**Comment by apuignav** [comment]
Shall we close this or we want to leave it for the more advanced tutorial?

**Comment by alexpearce** [comment]
:-1: on this for `first-steps` as it's a whole other ballgame, so :+1: for closing for now.

**Comment by betatim** [comment]
Meta: should we invent a label for things for "later lessons" so they don't
get lost? Or we rely on us remembering the interesting things?

**Comment by alexpearce** [comment]
Go for it.
