### ISSUE TITLE
Topic on decay descriptors

### ISSUE THREAD

**Issue by betatim** [lhcb/first-analysis-steps#61]
A new topic exclusively on decay descriptors.

How to make this comprehendible?

Some random snippets I have:

``` python
print_decay = appMgr.toolsvc().create('PrintDecayTreeTool', interface="IPrintDecayTreeTool")

# New style decay descriptors, also known as LoKi decays
loki_decay_finder = appMgr.toolsvc().create('LoKi::Decay', interface="Decays::IDecay")
# Old style decay descriptors
old_decay_finder = appMgr.toolsvc().create("DecayFinder", interface="IDecayFinder")

# works
#decay_desc = "[[B0]cc -> (^D- => {^K- ^K+ ^pi-, ^K- ^pi+ ^pi-,^pi+ ^pi- ^pi-, ^K- ^K- ^pi+}) ^K-]cc"
# doesn't work
decay_desc = "[[B0]cc -> (^D- => {^K- ^K+ ^pi-, ^K- ^pi+ ^pi-,^pi+ ^pi- ^pi-}) ^K-]cc"
old_decay_finder.setDecay(decay_desc)

#WS_candidates = evt['/Event/Bhadron/Phys/B02DKWSD2HHHBeauty2CharmLine/Particles']
#B = WS_candidates[0]
#print_decay.printTree(B)
# Can we find the decay?
#old_decay_finder.hasDecay(WS_candidates)

# Beware, you can not repeatedly call this. It somehow keeps track
# of how often it has been called/recursion stuff :-s
#head = Particle()
#old_decay_finder.findDecay(WS_candidates, head)
# head will contain the head of the decay tree
#print head
```

**Comment by seneubert** [comment]
There is a snipped that prints all possible particles that you can use. We should at least put that in.

**Comment by alexpearce** [comment]
I don't see a need to compare old and new. I could make a lesson, if we think it's necessary.

**Comment by alexpearce** [comment]
However, it is a [pretty complex issue](https://indico.cern.ch/event/262630/contribution/2).

**Comment by saschastahl** [comment]
Yes, for starters it is only confusing. This would be a good topic for "I haven't worked on software for two years but now I want do an analysis" people. You also don't teach people the spelling of words from a hundred years ago :).

**Comment by betatim** [comment]
Sorry, I didn't want to suggest we should do a comparison of old and new.
Simply dumped a bunch of "useful" code from a script I had. I think for the
moment we should keep this for `second-analysis-steps` instead of the
beginner one.

**Comment by alexpearce** [comment]
KK, close this?
