### ISSUE TITLE
SetpProject vs lb-run

### ISSUE THREAD

**Issue by betatim** [lhcb/first-analysis-steps#62]
We should make a decision and make sure we are consistent everywhere.

If we advertise `lb-run` we need to show off the `lb-run Project v1r2 $SHELL` trick. (Bonus points for making it modify the prompt to show what project you are in automagically ...)

**Comment by ibab** [comment]
This will be done in a lesson I split off from the general introduction.
I'll push it in a moment.
I'll also add a note that explains what `SetupProject` is.

**Comment by roelaaij** [comment]
I think it's important to emphasize that SetupProject is still supported, but deprecated the cmake builds and lb-run/run should be used whenever possible.

Since Ganga unfortunately doesn't handle it, although this is being worked on, I guess we're in a bit of a strange place...

**Comment by apuignav** [comment]
I would only teach lb-run to make sure people don't start with SetupProject
because it's easier. However, the lack of Ganga support is disturbing.

**Comment by betatim** [comment]
As I understand the lack of `ganga` support for `lb-run` is "irrelevant" for users here as we don't show them how to compile their own code for use with `ganga`. Is that right?

If we `lb-run` it, we need to tidy up these examples:
- [ ] 05-files-from-grid.md
- [ ] 05-interactive-dst.md
- [ ] 11-davinci-grid.md
