### ISSUE TITLE
Minimal local DV job to make minimal DecayTreeTuple

### ISSUE THREAD

**Issue by betatim** [lhcb/first-analysis-steps#7]
Given a local DST, run a minimal DV job over it to make a minimal DecayTreeTuple.

This will have to explain how to get stripping21 decisions (for the one chosen stripping line: http://lhcb-release-area.web.cern.ch/LHCb-release-area/DOC/stripping/config/stripping21/charmcompleteevent/strippingd2hhcompleteeventpromptdst2d2rsline.html) and use those as the file we download from the grid most certainly will have some "random" stripping

**Comment by ibab** [comment]
Do you have something like this in mind?
https://twiki.cern.ch/twiki/bin/view/LHCb/StrippingFAQ#How_do_I_run_some_stripping_line

**Comment by betatim** [comment]
Yes, that looks right.

The problem is that the simulated events you find in the book-keeping has a particular version of the stripping decisions already evaluated (but it keeps all events). So if we use `stripping21` for the data, then we should also use that for the simulated events.

**Comment by alexpearce** [comment]
Is this for running over MC or data?

**Comment by betatim** [comment]
A minimal DV job for data and for simulation.

In the data you can't redo the stripping, so the discussion of the stripping is for sim only

**Comment by ibab** [comment]
Are there arguments against using Stripping20 for the tutorials?
Rerunning the stripping here makes the exercise a bit non-minimal :)

**Comment by alexpearce** [comment]
I guess the argument against is that S21 is supposedly the ‘legacy stripping’, so if your data is available in S21 and you're starting a new analysis, that's what you should use. (I don't know how much of an official recommendation that is though.)

**Comment by betatim** [comment]
I like the idea of using stripping21 because that is what everyone will be
using soon no? (Maybe this assumption is wrong) So by using it we make the
tutorial slightly more future proof. Maybe do a round of minimal DV
without, then have a second iteration where we say "and now with
stripping21"?

**Comment by ibab** [comment]
Or maybe "this is how you access the stripping output" (using Stripping20) and then "oh, but we need to use Stripping21 -> rerun" in a second tutorial that follows this one?

Edit: Okay, realized that's identical to your suggestion :D

**Comment by betatim** [comment]
@ibab can you write this bit? Pleeeaassee

**Comment by alexpearce** [comment]
I'm already on it, but feel free to take over @ibab if you like.

**Comment by ibab** [comment]
I can do the follow-up once I know how this part is structured / what the options file looks like.

**Comment by betatim** [comment]
Ah, I'm too slow. Sort it out between yourselves :)

**Comment by alexpearce** [comment]
Options for data:

``` python
from GaudiConf import IOHelper
from Configurables import DaVinci, DecayTreeTuple
from DecayTreeTuple.Configuration import *

stream = 'CharmCompleteEvent'
line = 'D2hhCompleteEventPromptDst2D2RSLine'

dtt = DecayTreeTuple('TupleDstToD0pi_D0ToKpi')
dtt.Inputs = [
    '/Event/{0}/Phys/{1}/Particles'.format(stream, line)
]
dtt.Decay = '[D*(2010)+ -> ^(D0 -> ^K- ^pi+) ^pi+]CC'
dtt.addBranches({
    'Dst': '[D*(2010)+ -> (D0 -> K- pi+) pi+]CC',
    'Dst_pi': '[D*(2010)+ -> (D0 -> K- pi+) ^pi+]CC',
    'D0': '[D*(2010)+ -> ^(D0 -> K- pi+) pi+]CC',
    'D0_K': '[D*(2010)+ -> (D0 -> ^K- pi+) pi+]CC',
    'Dp_pi': '[D*(2010)+ -> (D0 -> K- ^pi+) pi+]CC'
})
dtt.ToolList = [
    'TupleToolGeometry',
    'TupleToolKinematic',
    'TupleToolPid',
    'TupleToolPrimaries',
    'TupleToolTrackInfo',
    'TupleToolEventInfo'
]
# Add the delta mass variable, dm = m(Kpipi) - m(Kpi)
dst_tt = dtt.Dst.addTupleTool('LoKi__Hybrid__TupleTool/DstTupleTool')
dst_tt.Variables = {
    'delta_M': 'M - M1'
}

DaVinci().UserAlgorithms += [dtt]
DaVinci().InputType = 'DST'
DaVinci().TupleFile = 'DVntuple.root'
DaVinci().PrintFreq = 1000
DaVinci().DataType = '2011'
DaVinci().Simulation = False
# Only ask for luminosity information when using collision data
DaVinci().Lumi = not DaVinci().Simulation
DaVinci().EvtMax = -1

IOHelper().inputFiles([
    './00041838_00047508_1.charmcompleteevent.dst'
], clear=True)
```

Tested by downloading an LFN and running DaVinci with

``` shell
$ lhcb-proxy-init
$ lb-run LHCbDirac dirac-dms-get-file /lhcb/LHCb/Collision11/CHARMCOMPLETEEVENT.DST/00041838/0004/00041838_00047508_1.charmcompleteevent.dst
$ lb-run DaVinci v36r6 gaudirun.py ntuple_options.py
```

Example output `DVntuple.root` available at

``` shell
$ cd /afs/cern.ch/user/a/apearce/public/for/lhcbFirstAnalysis/ntupleOptions
```

**Comment by alexpearce** [comment]
How do people feel about multiple options files? I often structure things like

```
- davinci_2011.py
- davinci_2012.py
- davinci_simulation.py
- stripped_ntuples.py
- run_stripping.py
```

Then when I want to create ntuples I can run

``` shell
$ gaudirun.py davinci_2011.py davinci_simulation.py stripped_ntuples.py
```

Might be something to just touch on (“If you find your options files getting long, or you're duplicating code between files, you can split them up like this…”).

**Comment by betatim** [comment]
Do you know how to make that happen with `ganga`?

If you are busy I will take what you posted above and add some prose to make a lesson out of it.

**Comment by alexpearce** [comment]
You just set the list of options files as `job.application.optsfile`.

When would you want the lesson by?

**Comment by betatim** [comment]
Ah, didn't know that!

Today? I wanted to write the "Mini DV on the grid" which builds on this, and @apuignav wanted to write something on LoKi functors, hence finishing this off first.

**Comment by alexpearce** [comment]
Leave it with me :+1:

**Comment by betatim** [comment]
Cool beans.

Can we make the minimal example even more minimal by removing the LoKi functor part? Do we need the branches part?

(Not sure what balance to strike between making things super-super-super simple and having too much fragmentation. Ideas? Maybe a good question to ask to find the answer is "can I explain all the options and run it in under 10minutes?" Too much fragmentation makes for too much overheads, on the other hand nicely modular things are easier to keep up to date :-/)

**Comment by alexpearce** [comment]
OK, I wasn't sure exactly how minimal you were after. If you want super-minimal, you only need to define the `Inputs` and the `Decay`.

**Comment by betatim** [comment]
And then we write another lesson about branches, LoKi functors, and tuple
tools? Maybe someone has opinions but I'd go for the super minimal for the
moment.

**Comment by alexpearce** [comment]
Looks like that split has already been set up in steps 12, 13, and 14, so yeah sure. We'll do as little as possible here, and build on the options file(s) later.

**Comment by ibab** [comment]
I may have found a few inconsistencies when reading through the tutorial:
- The last two links don't point anywhere
- The 'downloaded locally' link points to `03-bookkeeping`. Maybe this should be `05-files-from-grid`?
- Change the example file to `'./00035742_00000002_1.allstreams.dst'` (the MC file we downloaded earlier)
- Set `DaVinci().Simulation` to `True`
- Use DataType = '2012'
- Use the `AllStreams` stream

Are these valid corrections?
If yes, I can open a pull request.

**Comment by betatim** [comment]
Yes!

The second to last link should be `code/09-...py` and maybe we make the last link not a link at all? Unsure about how to distribute it.

Basically yes to all other questions.

**Comment by betatim** [comment]
This one is done. #10 will benefit from the tools and branches part that was posted above.
