### ISSUE TITLE
Improvements in the "Developing for LHCb" lession

### ISSUE THREAD

**Issue by apuignav** [lhcb/first-analysis-steps#80]
We need to add reminders so people update when they commit:
- The [LHCb tag collector](lhcb-tag-collector.web.cern.ch/lhcb-tag-collector/index.html)
- The `doc/release.notes` file

**Comment by betatim** [comment]
- keep an eye on the tests

**Comment by saschastahl** [comment]
I'll add that later today.

**Comment by betatim** [comment]
Is this done? How does it related to #120?

**Comment by saschastahl** [comment]
This is already in. For #120 I will add the example where we just changed some branches in the TupleToolDecayTreeFitter.

**Comment by betatim** [comment]
Ok, closing this one.
