### ISSUE TITLE
Bug in the selection script

### ISSUE THREAD

**Issue by seneubert** [lhcb/first-analysis-steps#84]
In https://github.com/lhcb/first-analysis-steps/blob/master/code/06-building-decays/build_decays.py#L14
the right property of CombineParticles is not the `Decay` but `DecayDescriptor`.
Have we tested this code snippet?

**Comment by seneubert** [comment]
Also, in https://github.com/lhcb/first-analysis-steps/blob/master/code/06-building-decays/build_decays.py#L21 you cannot pass Pions and Kaons. These objects are no Selections. I suspect you have to use the DataOnDemand service to get them. Testing this out now.

**Comment by apuignav** [comment]
Yes, I'm fixing the text. PR incoming...

On Tue, Jun 2, 2015 at 4:23 PM, Sebastian Neubert notifications@github.com
wrote:

> Also, in
> https://github.com/lhcb/first-analysis-steps/blob/master/code/06-building-decays/build_decays.py#L21
> you cannot pass Pions and Kaons. These objects are no Selections. I suspect
> you have to use the DataOnDemand service to get them. Testing this out now.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/lhcb/first-analysis-steps/issues/84#issuecomment-107971772
> .

## 

Dr. Albert Puig Navarro
Laboratoire de Physique des Hautes Energies
Ecole Polytechnique Fédérale de Lausanne (EPFL)
BSP 614.4 (Cubotron UNIL) CH-1015 Lausanne
EPFL Phone: 021 6939808
CERN Phone: 72518

**Comment by seneubert** [comment]
Good fix.
