### ISSUE TITLE
Add callout box to `11-davinci-grid.md` explaining SetupProject use

### ISSUE THREAD

**Issue by seneubert** [lhcb/first-analysis-steps#94]
The instructions in https://github.com/lhcb/first-analysis-steps/blob/master/11-davinci-grid.md using SetupProject work. I tried to switch to lb-run. This does not work.

Ganga.Utility                      : ERROR    Cannot construct environ:
(and more errors)

**Comment by apuignav** [comment]
Ganga does not support cmake right now. If it's not explicit in the text,
it should be added.

Albert

**Comment by betatim** [comment]
Can we change the title of this issue to "Add callout box to `11-davinci-grid.md` explaining SetupProject use" or some such. For the moment we need to use `SetupProject` for `ganga`, for the rest of the lessons we have `lb-run` so we need a short explanation what is going on.

**Comment by alexpearce** [comment]
`lb-run` is now recommended for every project (I think), including Ganga. Ganga also supports `lb-dev`-style applications now (see lhcb/second-analysis-steps#40), so I'll close this.
